services:
  - type: web
    name: Stadt_Biel
    env: python
    region: frankfurt
    plan: starter 
    
    nativeEnvironment:
      debian:
        preInstallCommands:
          - curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > /etc/apt/trusted.gpg.d/microsoft.gpg
          - echo "deb [arch=amd64] https://packages.microsoft.com/debian/11/prod bullseye main" > /etc/apt/sources.list.d/mssql-release.list
        packages:
          - unixodbc-dev
          - msodbcsql18

    buildCommand: "pip install -r requirements.txt"
    
    startCommand: "gunicorn --worker-class gevent --bind 0.0.0.0:$PORT app:app"
    
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - fromGroup: credential-secrets